version: '3'
services:
  neo4j:
    image: neo4j:4.2-community
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
